// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windows_Programing.Data;

#nullable disable

namespace Windows_Programing.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260522173459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDegree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 60,
                            MinDegree = 50,
                            Name = "C# Web Application Development"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 45,
                            MinDegree = 60,
                            Name = "ASP.NET Core MVC Basics"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            Dept_Id = 3,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Introduction to Python & AI"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            Dept_Id = 2,
                            Hours = 30,
                            MinDegree = 50,
                            Name = "Linux System Administration"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crs_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trainee_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Trainee_Id");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_Id = 1,
                            Degree = 95,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Crs_Id = 2,
                            Degree = 88,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Crs_Id = 1,
                            Degree = 55,
                            Trainee_Id = 2
                        },
                        new
                        {
                            Id = 4,
                            Crs_Id = 2,
                            Degree = 48,
                            Trainee_Id = 2
                        },
                        new
                        {
                            Id = 5,
                            Crs_Id = 3,
                            Degree = 92,
                            Trainee_Id = 3
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Dr. Ahmed Ali",
                            Name = "Software Development (SD)"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Dr. Sarah Kamal",
                            Name = "Open Source (OS)"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Dr. Nour Mansour",
                            Name = "Artificial Intelligence (AI)"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Crs_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Crs_Id = 1,
                            Dept_Id = 1,
                            Image = "ahmed.png",
                            Name = "Ahmed Mansour",
                            Salary = 15000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Crs_Id = 2,
                            Dept_Id = 1,
                            Image = "nouran.png",
                            Name = "Nouran Ezzat",
                            Salary = 18000.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            Crs_Id = 3,
                            Dept_Id = 3,
                            Image = "sarah.png",
                            Name = "Sarah Mahmoud",
                            Salary = 20000.0
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Dept_Id = 1,
                            Grade = "Excellent",
                            Image = "omar.png",
                            Name = "Omar Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Dept_Id = 1,
                            Grade = "Very Good",
                            Image = "mariam.png",
                            Name = "Mariam Youssef"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            Dept_Id = 3,
                            Grade = "Excellent",
                            Image = "ziad.png",
                            Name = "Ziad Tarek"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.CourseResult", b =>
                {
                    b.HasOne("Windows_Programing.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Windows_Programing.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("Trainee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Windows_Programing.Models.Instructor", b =>
                {
                    b.HasOne("Windows_Programing.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Windows_Programing.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
