// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windows_Programing.Data;

#nullable disable

namespace Windows_Programing.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260522192651_AddAuthenticationAndPermissions")]
    partial class AddAuthenticationAndPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Windows_Programing.Models.AppPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppPermissions");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppRolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AppRolePermissions");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDegree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 60,
                            MinDegree = 50,
                            Name = "C# Web Application Development"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 45,
                            MinDegree = 60,
                            Name = "ASP.NET Core MVC Basics"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            Dept_Id = 3,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Introduction to Python & AI"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            Dept_Id = 2,
                            Hours = 30,
                            MinDegree = 50,
                            Name = "Linux System Administration"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100,
                            Dept_Id = 5,
                            Hours = 50,
                            MinDegree = 50,
                            Name = "Data Analytics & Visualization"
                        },
                        new
                        {
                            Id = 6,
                            Degree = 100,
                            Dept_Id = 4,
                            Hours = 55,
                            MinDegree = 60,
                            Name = "Ethical Hacking & Penetration Testing"
                        },
                        new
                        {
                            Id = 7,
                            Degree = 100,
                            Dept_Id = 6,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Cloud Computing with Azure"
                        },
                        new
                        {
                            Id = 8,
                            Degree = 100,
                            Dept_Id = 3,
                            Hours = 60,
                            MinDegree = 60,
                            Name = "Deep Learning & Neural Networks"
                        },
                        new
                        {
                            Id = 9,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 48,
                            MinDegree = 50,
                            Name = "Advanced React & Next.js Framework"
                        },
                        new
                        {
                            Id = 10,
                            Degree = 100,
                            Dept_Id = 1,
                            Hours = 36,
                            MinDegree = 50,
                            Name = "Introduction to Database Systems"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crs_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trainee_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Trainee_Id");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_Id = 1,
                            Degree = 95,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Crs_Id = 2,
                            Degree = 88,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Crs_Id = 1,
                            Degree = 55,
                            Trainee_Id = 2
                        },
                        new
                        {
                            Id = 4,
                            Crs_Id = 2,
                            Degree = 48,
                            Trainee_Id = 2
                        },
                        new
                        {
                            Id = 5,
                            Crs_Id = 3,
                            Degree = 92,
                            Trainee_Id = 3
                        },
                        new
                        {
                            Id = 6,
                            Crs_Id = 9,
                            Degree = 98,
                            Trainee_Id = 4
                        },
                        new
                        {
                            Id = 7,
                            Crs_Id = 10,
                            Degree = 95,
                            Trainee_Id = 4
                        },
                        new
                        {
                            Id = 8,
                            Crs_Id = 5,
                            Degree = 88,
                            Trainee_Id = 5
                        },
                        new
                        {
                            Id = 9,
                            Crs_Id = 6,
                            Degree = 72,
                            Trainee_Id = 6
                        },
                        new
                        {
                            Id = 10,
                            Crs_Id = 3,
                            Degree = 94,
                            Trainee_Id = 7
                        },
                        new
                        {
                            Id = 11,
                            Crs_Id = 8,
                            Degree = 89,
                            Trainee_Id = 7
                        },
                        new
                        {
                            Id = 12,
                            Crs_Id = 7,
                            Degree = 64,
                            Trainee_Id = 8
                        },
                        new
                        {
                            Id = 13,
                            Crs_Id = 1,
                            Degree = 82,
                            Trainee_Id = 9
                        },
                        new
                        {
                            Id = 14,
                            Crs_Id = 2,
                            Degree = 78,
                            Trainee_Id = 9
                        },
                        new
                        {
                            Id = 15,
                            Crs_Id = 9,
                            Degree = 85,
                            Trainee_Id = 9
                        },
                        new
                        {
                            Id = 16,
                            Crs_Id = 6,
                            Degree = 58,
                            Trainee_Id = 10
                        },
                        new
                        {
                            Id = 17,
                            Crs_Id = 5,
                            Degree = 91,
                            Trainee_Id = 11
                        },
                        new
                        {
                            Id = 18,
                            Crs_Id = 7,
                            Degree = 60,
                            Trainee_Id = 12
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Dr. Ahmed Ali",
                            Name = "Software Development (SD)"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Dr. Sarah Kamal",
                            Name = "Open Source (OS)"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Dr. Nour Mansour",
                            Name = "Artificial Intelligence (AI)"
                        },
                        new
                        {
                            Id = 4,
                            Manager = "Dr. Kareem Fouad",
                            Name = "Cyber Security (CS)"
                        },
                        new
                        {
                            Id = 5,
                            Manager = "Dr. Laila Hassan",
                            Name = "Data Science (DS)"
                        },
                        new
                        {
                            Id = 6,
                            Manager = "Dr. Mostafa Kamel",
                            Name = "Cloud Computing & DevOps"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Crs_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Crs_Id = 1,
                            Dept_Id = 1,
                            Image = "ahmed.png",
                            Name = "Ahmed Mansour",
                            Salary = 15000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Crs_Id = 2,
                            Dept_Id = 1,
                            Image = "nouran.png",
                            Name = "Nouran Ezzat",
                            Salary = 18000.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            Crs_Id = 3,
                            Dept_Id = 3,
                            Image = "sarah.png",
                            Name = "Sarah Mahmoud",
                            Salary = 20000.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Maadi, Cairo",
                            Crs_Id = 6,
                            Dept_Id = 4,
                            Image = "kareem.png",
                            Name = "Kareem Fouad",
                            Salary = 22000.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Zamalek, Cairo",
                            Crs_Id = 5,
                            Dept_Id = 5,
                            Image = "laila.png",
                            Name = "Laila Hassan",
                            Salary = 21000.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nasr City, Cairo",
                            Crs_Id = 7,
                            Dept_Id = 6,
                            Image = "mostafa.png",
                            Name = "Mostafa Kamel",
                            Salary = 19000.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Giza, Egypt",
                            Crs_Id = 8,
                            Dept_Id = 3,
                            Image = "sherif.png",
                            Name = "Sherif Anwar",
                            Salary = 24000.0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Alexandria, Egypt",
                            Crs_Id = 9,
                            Dept_Id = 1,
                            Image = "yasmin.png",
                            Name = "Yasmin Soliman",
                            Salary = 17500.0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Heliopolis, Cairo",
                            Crs_Id = 10,
                            Dept_Id = 1,
                            Image = "tarek.png",
                            Name = "Tarek Nour",
                            Salary = 16000.0
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Dept_Id = 1,
                            Grade = "Excellent",
                            Image = "omar.png",
                            Name = "Omar Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Dept_Id = 1,
                            Grade = "Very Good",
                            Image = "mariam.png",
                            Name = "Mariam Youssef"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            Dept_Id = 3,
                            Grade = "Excellent",
                            Image = "ziad.png",
                            Name = "Ziad Tarek"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Giza, Egypt",
                            Dept_Id = 1,
                            Grade = "Excellent",
                            Image = "youssef.png",
                            Name = "Youssef Mohamed"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Zamalek, Cairo",
                            Dept_Id = 5,
                            Grade = "Very Good",
                            Image = "farida.png",
                            Name = "Farida Amr"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Maadi, Cairo",
                            Dept_Id = 4,
                            Grade = "Good",
                            Image = "hassan.png",
                            Name = "Hassan Soliman"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Heliopolis, Cairo",
                            Dept_Id = 3,
                            Grade = "Excellent",
                            Image = "salma.png",
                            Name = "Salma Khaled"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Alexandria, Egypt",
                            Dept_Id = 6,
                            Grade = "Pass",
                            Image = "nader.png",
                            Name = "Nader Ibrahim"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Tanta, Egypt",
                            Dept_Id = 1,
                            Grade = "Very Good",
                            Image = "dina.png",
                            Name = "Dina Yasser"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Mansoura, Egypt",
                            Dept_Id = 4,
                            Grade = "Good",
                            Image = "karim.png",
                            Name = "Karim Walid"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Sheraton, Cairo",
                            Dept_Id = 5,
                            Grade = "Excellent",
                            Image = "nourhan.png",
                            Name = "Nourhan Amr"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Rehab, Cairo",
                            Dept_Id = 6,
                            Grade = "Pass",
                            Image = "hady.png",
                            Name = "Hady Ahmed"
                        });
                });

            modelBuilder.Entity("Windows_Programing.Models.AppRolePermission", b =>
                {
                    b.HasOne("Windows_Programing.Models.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Windows_Programing.Models.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppUser", b =>
                {
                    b.HasOne("Windows_Programing.Models.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.CourseResult", b =>
                {
                    b.HasOne("Windows_Programing.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Windows_Programing.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("Trainee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Windows_Programing.Models.Instructor", b =>
                {
                    b.HasOne("Windows_Programing.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.HasOne("Windows_Programing.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Windows_Programing.Models.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Windows_Programing.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Windows_Programing.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Windows_Programing.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
